### ISSUE TITLE
有办法设置在action里获取url,通过邮件发送?

### ISSUE THREAD

**Issue by stilleshan** [embbnux/firefox-send-link-generator#1]
uses: dawidd6/action-send-mail@v2 这个action是可以发邮件的,不知道 body 内如何获取url的链接..
```
    - name: Send mail
      uses: dawidd6/action-send-mail@v2
      with:
        server_address: smtp.qiye.aliyun.com
        server_port: 465
        username: ${{ secrets.MAILUSERNAME }}
        password: ${{ secrets.MAILPASSWORD }}
        subject: GitHub Actions Auto ACME
        body: Build job of ${{github.repository}} completed successfully!
        to: xxx@xxx.com
        from: GitHub Actions
```
